Added trip date and distance to Packheader component
Packstack-Tech/public pull request #1
Opened 2024-01-05 03:11 UTC by eightfivezero

First off, I want to apologize for the unsolicited PR. 😅  
I realized that the trip date and distance are not shown on the public facing pack page so I thought it would be neat to add that information and here we are:

<img width="911" alt="image" src="https://github.com/Packstack-Tech/public/assets/1029855/d33e96c3-e9d5-4dd5-88e3-34125be5c6c1">

The date(s) only show if they're set and the distance only shows if it's higher than 0.

I tried matching the style of the site but if you want changes done to this, let me know and I will see what I can do. 🙏 
Obviously it's also okay to close the PR if that's not something you'd want on that page. 👍 

Note: This PR adds the `date-fns` package, as well as updates the `lucide-react` package to the latest version.

2024-01-06 04:16 UTC, maplethorpej requested changes
Thanks for jumping on this. I forgot this repo was open actually 😂

Your changes look great. I just need to update the trip endpoint to return the distance unit before we merge this.

2024-01-06 04:16 UTC, maplethorpej commented on src/components/PackHeader.tsx
> +            {trip.distance}km
The user can actually change the distance unit. I'll need to make a slight update to this endpoint to return the distance unit before we can merge this.

2024-01-06 05:17 UTC, eightfivezero commented
@maplethorpej Oh word, good catch! The missing distance unit was an oversight on my part. 🙈 Let me know when you made that update on the endpoint and I'll implement the change here. 👍

2024-01-06 19:23 UTC, maplethorpej commented
@eightfivezero I've added the `user` data to the response. Sync with `main` and you'll see the new response types and props passed to `PackHeader`.

Thanks again for adding this!

https://github.com/Packstack-Tech/public/pull/2

2024-01-06 20:56 UTC, eightfivezero commented
Awesome, thank you @maplethorpej 👍 Please have another look now!

2024-01-07 02:52 UTC, maplethorpej requested changes
Two more small things and then we're good

2024-01-07 02:52 UTC, maplethorpej commented on src/components/PackHeader.tsx
> +            {`${trip.distance} ${user.unit_distance}`}
Small thing, but this can just be `{trip.distance} {user.unit_distance}`

2024-01-07 02:52 UTC, maplethorpej commented on src/components/PackHeader.tsx
> +  console.log(user)
Remove log

2024-01-07 03:06 UTC, eightfivezero commented
@maplethorpej Oopsie 🙈

2024-01-07 19:02 UTC, maplethorpej approved these changes
Perfect, thanks for the update!

2024-01-07 19:03 UTC, merged